version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "YOUR_STACK_NAME"
s3_bucket = "YOUR_S3_BUCKET_NAME"
s3_prefix = "YOUR_S3_PREFIX"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
