AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template for test-sam-app
Globals:
  Function:
    Runtime: python3.9
    Timeout: 3

Resources:
  IndexFunctionLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.lambda_handler
      CodeUri: function/
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET


Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
